set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports {note[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {note[0]}]
set_property PACKAGE_PIN R1 [get_ports {note[0]}]
set_property PACKAGE_PIN N4 [get_ports {note[1]}]
set_property PACKAGE_PIN M4 [get_ports {note[2]}]
set_property PACKAGE_PIN R2 [get_ports {note[3]}]
set_property PACKAGE_PIN P2 [get_ports {note[4]}]
set_property PACKAGE_PIN P3 [get_ports {note[5]}]
set_property PACKAGE_PIN P4 [get_ports {note[6]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property IOSTANDARD LVCMOS33 [get_ports vol]
set_property PACKAGE_PIN M6 [get_ports vol]

set_property IOSTANDARD LVCMOS33 [get_ports {led_note[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_note[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {choose[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[0]}]
set_property PACKAGE_PIN G2 [get_ports {choose[7]}]
set_property PACKAGE_PIN C2 [get_ports {choose[6]}]
set_property PACKAGE_PIN C1 [get_ports {choose[5]}]
set_property PACKAGE_PIN H1 [get_ports {choose[4]}]
set_property PACKAGE_PIN G1 [get_ports {choose[3]}]
set_property PACKAGE_PIN F1 [get_ports {choose[2]}]
set_property PACKAGE_PIN E1 [get_ports {choose[1]}]
set_property PACKAGE_PIN G6 [get_ports {choose[0]}]
set_property PACKAGE_PIN L1 [get_ports {led_mode[2]}]
set_property PACKAGE_PIN M1 [get_ports {led_mode[1]}]
set_property PACKAGE_PIN K3 [get_ports {led_mode[0]}]
set_property PACKAGE_PIN G4 [get_ports {led_note[6]}]
set_property PACKAGE_PIN G3 [get_ports {led_note[5]}]
set_property PACKAGE_PIN J4 [get_ports {led_note[4]}]
set_property PACKAGE_PIN H4 [get_ports {led_note[3]}]
set_property PACKAGE_PIN J3 [get_ports {led_note[2]}]
set_property PACKAGE_PIN J2 [get_ports {led_note[1]}]
set_property PACKAGE_PIN K2 [get_ports {led_note[0]}]
set_property PACKAGE_PIN R3 [get_ports {mode[2]}]
set_property PACKAGE_PIN T3 [get_ports {mode[1]}]
set_property PACKAGE_PIN T5 [get_ports {mode[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_left[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_left[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_left[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_left[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_left[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_left[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_left[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_left[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_right[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_right[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_right[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_right[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_right[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_right[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_right[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_right[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports led_high_note_control]
set_property IOSTANDARD LVCMOS33 [get_ports led_low_note_control]
set_property PACKAGE_PIN K1 [get_ports led_low_note_control]
set_property PACKAGE_PIN H6 [get_ports led_high_note_control]





set_property IOSTANDARD LVCMOS33 [get_ports {low_note_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {low_note_control[0]}]
set_property PACKAGE_PIN U3 [get_ports {low_note_control[1]}]
set_property PACKAGE_PIN U2 [get_ports {low_note_control[0]}]

set_property DRIVE 16 [get_ports speaker]
set_property SLEW FAST [get_ports speaker]

set_property IOSTANDARD LVCMOS33 [get_ports {select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select[0]}]
set_property PACKAGE_PIN V4 [get_ports {select[0]}]
set_property PACKAGE_PIN V5 [get_ports {select[1]}]
set_property PACKAGE_PIN V2 [get_ports {select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN P5 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P15 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {led_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_select[0]}]
set_property PACKAGE_PIN H5 [get_ports {led_select[2]}]
set_property PACKAGE_PIN J5 [get_ports {led_select[1]}]


set_property PACKAGE_PIN K6 [get_ports {led_select[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]

set_property PACKAGE_PIN F5 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN C6 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN C7 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN E6 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN E5 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN E7 [get_ports {vga_rgb[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]


set_property PACKAGE_PIN C4 [get_ports vsync]


set_property PACKAGE_PIN D7 [get_ports hsync]


set_property DRIVE 12 [get_ports vol]
